doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            championship_id: App\Infrastructure\Doctrine\DBAL\Type\ChampionshipIdType
#            championship_status: App\Infrastructure\Doctrine\DBAL\Type\ChampionshipStatusType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Doctrine/ORM/Mapping/'
                prefix: 'App\Domain\Entity'
                alias: App
